### ISSUE TITLE
Files are gone after a reboot

### ISSUE THREAD

**Issue by kloknibor** [area515/Photonic3D#105]
Hi,

After I reboot my respberry pi all uploaded files are gone. Would it be possible to safe these somewhere and decide on your own if you want delete them? (So an delete button for every printable)

Thanks

**Comment by kloknibor** [comment]
I notice that for some reason on windows it doesn't delete the files... (atleast there's an image file still present on windows) But the raspberry pi did

**Comment by WesGilster** [comment]
That's very weird. We don't delete printables from disk. PrintJobs are only in memory, so they get wiped out on restart. Are you sure you are losing printables?

**Comment by kloknibor** [comment]
Yes I do alough the printables have become printjobs... I will try to make soem proof along with the logs for you in a couple of days ;)!

**Comment by WesGilster** [comment]
I've never been able to reproduce this issue if this is related to us saving to tmp we can fix this by adding this to your config.properties:
printdir=somedir
uploaddir=someotherdir

This will keep those directories out of tmp storage.

**Comment by kloknibor** [comment]
Hmm sorry I promised to give you logs a while back... I'll do a clean install from stable version, upload files, reboot and send you the logs tonight ;)! Should I record to prove I'm not crazy? Haha ;) just kidding. I'll move try the different upload dir too ;)

**Comment by WGAndrew** [comment]
If it helps, I've found that printables are volatile too. Whenever I restart a pi, they do just disappear until they're re-uploaded.

**Comment by WesGilster** [comment]
This has been fixed long ago in two different ways:
1. In production with the above uploaddir
2. In my current dev version without the above uploaddir fix.

**Comment by WesGilster** [comment]
Closed in cwh-1.0.0-beta3.
