### ISSUE TITLE
Add more than 1 slicing profile when adding printer

### ISSUE THREAD

**Issue by kloknibor** [area515/Photonic3D#229]
Hi,

I think it would be great if we could download more slicing profiles depening on the printer chosen. So if we choose photocentric LC 10" that all files will get downloaded to the slicing profile folder.

I think easiest is to make a folder just like printers (or inside printers) with sub folders of with names of the supported printers and pull the profiles from there.

Let me know what you guys think.

**Comment by WesGilster** [comment]
Yeah, that sounds great, but I'm looking at doing something a little bit more cohesive than throwing everyone's data into a global location like github.

**Comment by kloknibor** [comment]
Ahh okay, I wouldn't think that slicing profiles would matter. Feel free to use the server if needed!

**Comment by WesGilster** [comment]
Thanks, it's not really a question of storage. Every host already holds it's own data, it's more a question of computing and IO right now.

**Comment by WesGilster** [comment]
I believe you have already solved this bug Robin. We are now able to create multiple slicing profiles and ink configs. Will close if you have no objections.
