### ISSUE TITLE
Any reason for not using JCenter

### ISSUE THREAD

**Issue by WesGilster** [area515/Photonic3D#282]
@jmkao I thought I'd ask our build expert if there was any reason we were using Maven Central instead of JCenter. I don't mind either way, but I've been experimenting with the JMonkeyEngine a bit and the artifacts aren't available on Maven Central. I've added jcenter into the build, but I thought I'd ask a bit before I checked it in.

**Comment by jmkao** [comment]
No particular reason, I think I may have copied that section from a template without looking too closely at the differences between Maven repos.

**Comment by WesGilster** [comment]
Sounds good. I'll keep them both then.
