### ISSUE TITLE
how to add slicing and ink profiles

### ISSUE THREAD

**Issue by kloknibor** [area515/Photonic3D#294]
Hi,

Is there any easy way to add (and than also remove) slicing and ink profiles? an API for such would be great :)

Kind regards

**Comment by WesGilster** [comment]
Done. I didn't realize I didn't have those... I added backend CRUD RESTful methods for slicing profiles and machine configs into the MachineService. Also added a test for these new methods.

On the other hand, many InkConfigs can already be contained and are specific to a single SlicingProfile and can be manipulated completely on the GUI side. That is the same way CW organized it's file structure, and that setup actually seems to make sense. Let me know if there are any RESTful changes required in that area as I really don't see it.

**Comment by kloknibor** [comment]
Thanks Wes! 

You are awesome :)! I agree with you only the slicingprofiles will be fine and swagger looked nice ;)!

thanks a lot!

**Comment by kloknibor** [comment]
you might have created some errors with your latest release ;)! :  

![image](https://cloud.githubusercontent.com/assets/10560390/20620751/23cf7770-b2f3-11e6-8da1-34adf0e629ae.png)

**Comment by WesGilster** [comment]
Ouch didn't see that. New build running.
