### ISSUE TITLE
[bug] not always being properly connected to the motor controller

### ISSUE THREAD

**Issue by kloknibor** [area515/Photonic3D#300]
Hi,

I've got an issue where the software thinks it is properly connected and I can control the screen. But when I try to send commands manually it doesn't reply on the command and just won't do anything. After stopping and restarting the printer everything is fine again. This is incidentally and not all the time.

[LogBundle (16).zip](https://github.com/area515/Photonic3D/files/690372/LogBundle.16.zip)

**Comment by WesGilster** [comment]
There was already some work in this area. Your fork is not up to date with the latest version of development. You'll need to pull and rebuild from development first.

**Comment by WesGilster** [comment]
Closing for now since this is related to a bug that is fixed in development.
