### ISSUE TITLE
[BUG] - empty notification windows Wes version

### ISSUE THREAD

**Issue by kloknibor** [area515/Photonic3D#304]
![image](https://cloud.githubusercontent.com/assets/10560390/23135533/fbba3ef4-f790-11e6-8d15-a514f0fe0847.png)

Hi , in the development version of wes I get the following blank notification when uploading an .cws file. Got this with all .cws files i tried, I attached one : 
[Ag test robin.cws.zip](https://github.com/area515/Photonic3D/files/788132/Ag.test.robin.cws.zip)

**Comment by WesGilster** [comment]
I'm not able to reproduce this. I have noticed that when I started floating between different versions of photonic and different repos that there was some fairly strange functionality that would occur if I didn't dump my browser cache. If this doesn't work for you, I'll need to see a log dump and perhaps see the last network responses in the browser debug mode. I'll check a couple more things to see if I can recreate this.

**Comment by kloknibor** [comment]
I think this is something in my own front-end. It is an error notification which is not filled. I see I used my own front-end on top of your front-end in the screenshot) (Which I thought I didn't)

With the latest merge of your repo I have the same issue now, So if you can't reproduce it is an problem for me ! Sorry to bother...
