### ISSUE TITLE
(Question)How to set up my DLP printer in photonic3D?

### ISSUE THREAD

**Issue by Jolly2015** [area515/Photonic3D#308]
Sorry I am a new user of DLP machine. I installed Raspberry Pi System Image. now I can visit dashboardPage, 
then I installed "Photonic3D-windows64-offline.exe" on my win7 x64, when I click it,after the read picture,it return to dashboardPage,no informtion to install photonic3d,what shold I do?

**Comment by WesGilster** [comment]
That's it. You've done it. Now it's time to setup a printer or use a community profile. You don't really even need the windows install, since it seems like you already know how to get to the dashboard without it. The windows install is just for those that don't know how to browse to the dashboard.

Not sure where you want to go next, but here are some docs if you are interested:
https://wiki.photonic3d.com/doku.php

**Comment by Jolly2015** [comment]
@WesGilster,thanks for your fast answer,I would like to know how to set up a printer next,beacuse there is no  printer shows on the dashboard page even I connected my machine.I try to flowing the instruction(from your link at "plug and play" part) , just a red Photonic3D picture come out,then open a dashboard page still without any prints,should I do something change on my raspberry pi? How Photonic3D communicate with my ramps1.4?How it know the bandrate and serial port number?

**Comment by WesGilster** [comment]
Click on "printers" on the dashboard page. Then you'll find the set of community printers that are available to install automatically. If none of these meet your needs you can click on the "Create" button. That will allow you to setup all of the settings you are looking for. From this point on, everything should be gui setup.

**Comment by WesGilster** [comment]
I'll need two things:
1. Provide a screenshot of your printers page 
2. Click the "download" button on any page of Photonic3d and upload that zip file to this forum.

That should give us enough information to go on.

**Comment by Jolly2015** [comment]
@WesGilster OK, thanks,here is the link,
https://github.com/Jolly2015/Photonic3D-error-log?files=1

**Comment by Jolly2015** [comment]
Then I change  google browser and now I can create a printer on printersPage, but when I click "start",  it said "Failed to assign PrinterFirmware for Autodetect 3d printer firmware",I think the marlin firmware should be modify somewhere and I am try it now.

**Comment by Jolly2015** [comment]
Everything is OK now:
1.Use chrome browser
2.Use right firmware

**Comment by jmkao** [comment]
What browser were you using before that didn't work?

**Comment by WesGilster** [comment]
Yeah I would like to know that as well. I test mostly with Chrome, but would like to know what problems you might be having.

**Comment by Jolly2015** [comment]
@jmkao @WesGilster  I using 360 Browser before, can I change language for Photonic3D, If yes, is there any instruction?

**Comment by kloknibor** [comment]
@Jolly2015 we don't have translations for photonic3D I'm afraid. However what you could do is google translate from the chrome browser on photonic :)!

**Comment by Jolly2015** [comment]
I can understand that, I just saw another  country's language  version somewhere,  so I am very curious if I can ,LOL

**Comment by kloknibor** [comment]
@Jolly2015 most text is hardcoded throughout everywhere in the code basically :P So at this point translating would be quite an task! But who knows maybe in the future :)!

**Comment by kloknibor** [comment]
Also we had some trouble in IE11 and rewrote the function in settings.js to this (code is outdated I''m merging with Wes's code currently ) : 

```
function refreshSelectedPrinter(printerList) {
        	var foundPrinter = false;
        	if (printerList.length == 1 &&  controller.autodirect != 'disabled') {
        		controller.currentPrinter = printerList[0];
        		foundPrinter = true;
        	} else {
        		var printersStarted = 0;
        		var currPrinter = null;
	        	for (var i = 0; i < printerList.length; i++) {
				// had to change as for ___ of ____ isn't supported in IE11 :(
	        		if (printersStarted > 1) {
	        			break;
	        		}
	        		if (printerList[i].started) {
	        			printersStarted += 1;
	        			currPrinter = printerList[i];
	        		}
	        		if (controller.currentPrinter != null && printerList[i].configuration.name === controller.currentPrinter.configuration.name) {
	        			controller.currentPrinter = printerList[i];
	        			foundPrinter = true;
	        		}
	        	}
	        	if (printersStarted == 1 && controller.autodirect != 'disabled') {
	        		controller.currentPrinter = currPrinter;
	        		foundPrinter = true;
	        	}
        	}
        	if (!foundPrinter) {
        		controller.currentPrinter = null;
        	}
        }
```

**Comment by WesGilster** [comment]
Google has a nice little "translate" button that they can add to your 
page. Probably the easiest route for now.

**Comment by WesGilster** [comment]
Setup a pull request to my dev repo for that change and I'll take a look at it and see if I can merge it in.

**Comment by WesGilster** [comment]
This code was merged in from Robin's repo fairly recently.
