### ISSUE TITLE
cancel print or pause print do not close shutter

### ISSUE THREAD

**Issue by jschoch** [area515/Photonic3D#315]
I think the default shutter position should be closed and that the user can open the shutter if they need to via the motor controls.  currently the shutter stays open if you pause or cancel a print job.

**Comment by WesGilster** [comment]
I made a quick fix for this in the dev repo, but it seemed as though the pause should have already worked. Let me know if it works for you...

When the build finishes it will be: WesGilster-b5d2029

**Comment by WesGilster** [comment]
Fix was committed long ago and it's been over a month. Closing
