### ISSUE TITLE
[BUG] : double skinName needed in API request

### ISSUE THREAD

**Issue by kloknibor** [area515/Photonic3D#339]
Hi,

I'm just playing with the new activate and de-activate API requests but I currently need to request it as : 

services/settings/skins/activate/" + skinName, skinName

it would make more sense to put to services/settings/skins/activate/ with the body skinName. It currently feels a bit double.

**Comment by WesGilster** [comment]
Take my last changes. I've thrown out the activate/deactivate and fixed the gui so that you can save the full skin from the GUI including the active flag.
