### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by tjfreckles** [area515/Photonic3D#346]
I don't know if questions and issues are still being answered, but here goes.
I'm a bit of a noob when it comes to Rpi and so if I'm not including enough information please tell me what you need.

I installed the raspbian stretch image (from unzipping photonic3d) and formatted it and wrote it to my SD card. For instructions on how to download and format I was following this video: 

https://www.youtube.com/watch?v=ng1Sj2ktWhU

Up to the point where he ran the commands headless. I opened the terminal in my Rasp pi, I expanded the file system (not really sure what that does, but I did it) I enabled camera and then in my terminal I typed the commands: 

sudo wget start.sh https://github.com/area515/Photonic3D/raw/master/host/bin/start.sh
sudo chmod 777 start.sh
sudo ./start.sh

Like the guy in the video and the first two commands *seemed* to get the same responses as the guy in the video, but when I typed the final command my response was significantly shorter ending with something along the lines of searching for printers or something (I rebooted afterwards so the exact response is gone). I'll try to get more info if you tell me what you need to help and how I need to get it, I think my model is a 3B and if the issue could possibly be my pi not getting enough power then that would make sense given the cord i'm stuck with right now, but let me know if that'd make sense please. Thank you very much

**Comment by WesGilster** [comment]
That's not quite enough to go on. We'll need to see the output of that last command to help you out.

**Comment by gesatpal** [comment]
Hi,

i think that has something to do with the Java Links in the start.sh script. I had the same issue the installation stops because of the "to old" Java Links. Just try to use the normal Image and then upgrade to the development version. That works at least for me.

**Comment by tjfreckles** [comment]
@gesatpal Idk what you mean by the normal image? The normal photonic3d image? Noobs? just raspbian? 

@WesGilster I tried the same commands again without wiping my system (I can't seem to find my micro sd to usb stick) And this was the result. It looks like it thinks its installed but in the video I watched they said that when I turn on my pi it should boot right up with creation workshop and it didn't.

login as: pi
pi@10.0.0.91's password:
Access denied
pi@10.0.0.91's password:
Linux photonic3d 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed May  9 23:17:08 2018

SSH is enabled and the default password for the 'pi' user has not been changed.
This is a security risk - please login as the 'pi' user and type 'passwd' to set a new password.

pi@photonic3d:~ $ sudo wget https://github.com/area515/Creation-Workshop-Host/raw/master/host/bin/start.sh
--2018-05-16 19:04:14--  https://github.com/area515/Creation-Workshop-Host/raw/master/host/bin/start.sh
Resolving github.com (github.com)... 192.30.255.112, 192.30.255.113
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/area515/Photonic3D/raw/master/host/bin/start.sh [following]
--2018-05-16 19:04:14--  https://github.com/area515/Photonic3D/raw/master/host/bin/start.sh
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/area515/Photonic3D/master/host/bin/start.sh [following]
--2018-05-16 19:04:14--  https://raw.githubusercontent.com/area515/Photonic3D/master/host/bin/start.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.52.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.52.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6954 (6.8K) [text/plain]
Saving to: ‘start.sh’

start.sh            100%[===================>]   6.79K  --.-KB/s    in 0.001s

2018-05-16 19:04:15 (4.59 MB/s) - ‘start.sh’ saved [6954/6954]

pi@photonic3d:~ $ sudo chmod 777 start.sh
pi@photonic3d:~ $ sudo ./start.sh
Local Config: /root/3dPrinters/config.properties
mv: cannot stat 'cwh-.*.zip': No such file or directory
Checking for new version from Github Repo: area515/Creation-Workshop-Host
Local Tag: 1.0.16
Network Tag: 1.0.16
No install required
Turning off screen saver and power saving
Determinging if one time install has occurred
Starting printer host server
pi@photonic3d:~ $

**Comment by tjfreckles** [comment]
It could just be I'm misunderstanding how to use photonic once it's installed. I'm not really an expert on Raspberry Pi's

**Comment by tjfreckles** [comment]
I'm gonna close this issue, I realized I didn't know what I was talking about, it did install and work, I just couldn't access it from my school's wifi/Lan internet. i still have no idea how to set up a printer though, but I'm looking through other issues to try and get help
