### ISSUE TITLE
Make a version that pulls resources from CDN.

### ISSUE THREAD

**Issue by WesGilster** [area515/Photonic3D#55]
At the moment the Raspberry Pi is hosting all resources and that puts quite a load on it. I could easily modify the build such that it you can run a version that downloads resources from a CDN. That way you could modify your config.properties like this:
hostGUI=resourcesCDN

...and it would take quite a bit of load off the Raspberry Pi. Keep in mind, this would force all of your CWH clients to have Internet access... It's a tradeoff, but your Pi could be light and fast.

**Comment by DanielJoyce** [comment]
Eh, if the proper cache headers are being sent this won't be an issue after the first browser load.

**Comment by WesGilster** [comment]
Yeah, I've had second thoughts about this as well.

**Comment by kloknibor** [comment]
Shall we close this then? I agree that with cache this should be sufficient  + it allows the user to only have an internal local network connection without acces to he internet

**Comment by WesGilster** [comment]
Yeah it's awfully pointless...
